site_name: MkDocs Demo
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: deep orange
      accent: deep orange
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: deep orange
      accent: deep orange

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jeevanpuhan
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jeevanpuhan
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jeevan-puhan

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/jeevanpuhan" target="_blank" rel="noopener">Jeevan Puhan</a>
